version: '3.4'

services:
    mssql-server:
     image: mcr.microsoft.com/mssql/server:2022-latest
     environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "numsey#2021"
      MSSQL_PID: Express
     ports:
        - "1433:1433"
     volumes:
        - C:\dados\volumes\sqlserver:/var/opt/mssql/data
    graphqlapi:
     image: ${DOCKER_REGISTRY-}graphqlapi
     build:
      context: .
      dockerfile: GraphQLAPI/Dockerfile
     environment:
      DbServer: "mssql-server"
      DbPort: "1433"
      DbUser: "SA"
      Password: "numsey#2021"
      Database: "GestaoProdutos"
